### ISSUE TITLE
Change in foldl' type signature in minor release breaks downstream packages

### ISSUE THREAD

**Issue by snoyberg** [serokell/universum#108]
I just spent a while trying to debug breakages around a number of packages from the serokell org while building LTS 10.2. As far as I can tell, the main problem is that universum-1.0.2 has a different signature for foldl' than universum-1.0.0. After a lot of fumbling, I ended up having to put upper bounds for LTS 10 on most of the serokell packages.

**Comment by snoyberg** [comment]
Seems like this is due to https://github.com/serokell/universum/issues/91

**Comment by ChShersh** [comment]
@snoyberg You're absolutely right regarding the reason of breakage. But currently there's only one Serokell package in Stackage which depends on `universum` according to this:

* https://github.com/fpco/stackage/blob/e2f6fb3a6dd022f86b07b2665cfe0fc2f3859d33/build-constraints.yaml#L2960

It's `log-warper`. And this was fixed for `log-warper`. `importify` is already dropped down from Stackage due to problems with `haskell-names`. I opened PR in `haskell-names` library and seems like this can't be fixed easily...

* https://github.com/haskell-suite/haskell-names/issues/103

Other Serokell package don't even use `universum-1.0.0`. So I understand that in general by changing type signature of function should in result in bumping up major version of package instead of minor. But I guess it's ok since there's only one active package in Stackage which depends on `universum` and we can fix problems for this package quite fast.

**Comment by snoyberg** [comment]
importify is still in LTS 10, even though it was dropped from Stackage
Nightly. Currently, I had to put upper bounds on both log-warper and
universum in LTS 10. I'm not telling you how to manage version bumps and
breaking changes, that's entirely your call. I'm just bringing to your
attention that it caused your packages to be held back in LTS Haskell.

**Comment by ChShersh** [comment]
Type of `foldl'` is changed back in `universum-1.1.0`. `universum` versions with confusing type of `foldl'` and bad version management are deprecated on Hackage. Latest `universum` is in latest stable LTS. So I guess this issue is fixed and can be closed. Regarding `importify`: there're other packages which stops `importify` from being added to LTS so I don't think that `universum` is the only blocking thing for this.
