### ISSUE TITLE
Add foldl1'

### ISSUE THREAD

**Issue by neongreen** [serokell/universum#11]
It's present in `Data.List` but not in `Data.Foldable` and thus isn't exported. We should add a `Foldable` version by ourselves.

**Comment by ChShersh** [comment]
This function is not safe. And because of this fact I don't want to export it in `Universum`. We don't want to suggest people using unsafe functions. It would be better to export `foldl'` instead of `foldl` because `foldl` is like «never use this function».

**Comment by volhovM** [comment]
@ChShersh 
> we don't want to suggest people using unsafe functions
So we're prohibiting usage of `fromJust`, `head` and all related obviously useful functions? I agree with @neongreen, it's better to export all folds, including strict versions because at most situations they are to be used, not lazy equivalents. And there's no safety problem IMO. Imagine the situation when function contract is "non-empty list passed" with guard on the opposite that throws error. It's a common usecase.

**Comment by ChShersh** [comment]
@volhovM
> So we're prohibiting usage of fromJust, head and all related obviously useful functions?

Well, yes. We already prohibited `head` and our `head` returns `Maybe`. We have all old functions with names like `unsafe(Head|Tail|Last|Init|At)`. Instead of using `fromJust` it is better to use `fromMaybe`. And usages of `fromMaybe` can be very cute if we introduce `(?:) = flip fromMaybe` which is so-called _elvis-operator_.

**Comment by gromakovsky** [comment]
I agree with @volhovM about unsafe functions. They should be discouraged, but not completely prohibited.

But, well, it sounds reasonable that we shouldn't put discouraged functions to `Universum`.

**Comment by neongreen** [comment]
Okay, then I'm closing the issue.
