### ISSUE TITLE
Return back 'Unsafe' module

### ISSUE THREAD

**Issue by ChShersh** [serokell/universum#128]
Sometimes you need to use unsafe functions like `head` because you can't prove everything.

So maybe it's a good idea to return back `Unsafe` module which should be exported qualified like this:

```haskell
import qualified Universum.Unsafe as Unsafe
```

And then you can use

```haskell
foo = Unsafe.head []
```

Current solution:

```haskell
import qualified Data.List as List

foo = List.head []
```

**Comment by Martoon-00** [comment]
I love qualified variant much more than `unsafeHead` and others

**Comment by volhovm** [comment]
I vote for bringing back `Unsafe` and shortening the names. How about `uHead` and `uLast`? Sometimes i write a lot of code in a hurry and i don't really care about type safety, so i only use unsafe variants. `List.head` is too long.

**Comment by int-index** [comment]
> How about uHead and uLast? 

I dislike this for several reasons:

* `u` does not necessarily stand for `unsafe`
* I no longer have `unsafe` as a visual cue for "read carefully"
* this introduces a new prefix rather than using a conventional one
* this invites people to use these names (as they're short), but we should actually discourage unsafe functions

**Comment by volhovm** [comment]
Ok whatevs, then `import Data.List as L` will do it for me.

**Comment by int-index** [comment]
> Ok whatevs, then import qualified Data.List as L will do it for me.

You can't just do that, you also need to add a comment that explains why your use of `List.head` is safe. There's really no reason to play code golf with unsafe functions.

**Comment by volhovm** [comment]
@int-index the talk is not about how CSL should be written, i just love using `head` in my personal projects because the cost of failure is much lower than the cost of me doing this terrible `fromMaybe (error "this should never happen") <$> head ...` every time i need to take a head. It's fine to use unsafe functions, we give user the choice.

**Comment by ChShersh** [comment]
> the cost of failure is much lower than the cost of me doing this terrible fromMaybe (error "this should never happen") <$> head ...

I think it's okay to use unsafe `head` if it's completely obvious from context that this usage is safe. But then: it it's obvious, why not write code in safe way and avoid possible error? I saw several places in CSL where it's actually hard to refactor code to not use `Unsafe.head`. But at the same it wasn't so obviouos. So I think we should still have unsafe versions.

Personally I don't like to see `Impossible happened` error messages. While we don't have stack traces in Haskell, I don't think that cost of using `head` is low. So I don't see value in having short name for `Unsafe.head`. This function shouldn't be used often. Personally I never used unsafe `head`. Somehow I manage to write code without unsafe head. 

Though, with proposed structure one can write:

```haskell
import Universum hiding (head)
import Universum.Unsafe (head)
```

**Comment by ChShersh** [comment]
Unsafe functions we want to have:

1. `head`
2. `tail`
3. `last`
4. `init`
5. `at` (alias to `!!`)
6. `fromJust`
