### ISSUE TITLE
Monad.Catch & etc.

### ISSUE THREAD

**Issue by georgeee** [serokell/universum#13]
Need to:
- import everything from Control.Monad.Catch module
- get rid of MonadError imports
- get rid of `catch` and whatsoever

**Comment by ChShersh** [comment]
I think that _import everything from Control.Monad.Catch module_ is very bad decision.
Now we have next exports related to errors somehow:

* [Control.Monad.Except](https://github.com/serokell/universum/blob/master/src/Universum.hs#L119)
* [Control.Exception](https://github.com/serokell/universum/blob/master/src/Universum.hs#L166)
* [throwIO](https://github.com/serokell/universum/blob/master/src/Universum.hs#L216)
* [throwTo](https://github.com/serokell/universum/blob/master/src/Universum.hs#L219)

I need to know with what exact definitions do you have problems?

**Comment by georgeee** [comment]
At least we should get rid of `MonadError` and various `runExcept` stuff. It's not used anywhere

But like everywhere we use exceptions we use Monad(Throw|Catch|Mask)`, so at least this classes and their members and some functions should be imported

**Comment by gromakovsky** [comment]
> import everything from Control.Monad.Catch module

Nowadays we have everything from `Control.Exception` except `assert, displayException, throw, throwIO, throwTo`. The first three functions are not exported because they are not exported, the last two functions are lifted into `MonadIO`.

1. Since we use `MonadThrow` and others in many places, I agree that if there is version of function from `Control.Exception` generalized to `MonadCatch`/`MonadMask`, we should export this version. I also don't object to exporting type classes.
2. The only function which is in `Control.Monad.Catch` but not in `Control.Exception` is `throwM`. And it's the only throwing function in `Control.Monad.Catch`. So we should decide what to do with `throwM`, `throwIO`, `throw`, `ioError`, `throwTo`. Correct me if I am wrong, but I think these are all throwing functions in both modules. I would leave only `throwM` in `Universum`, taking `time-warp` into account.
3. Since we started this issue, let's also discuss whether we really need everything from `Control.Exception` that we currently have and whether we don't need what we don't have. For example, I think `assert` is a good function to be in `Universum`. In the best case we will start using `assert` quite often and it will make debugging easier :)
I am not sure about `Handler` because you may want to have your own type called `Handler` and about masking functions because we don't know how to use them, right? :)

> At least we should get rid of MonadError and various runExcept stuff. It's not used anywhere

I think it's a cool class and it's used in rscoin. I think `MonadError` is a very good think for pure code which can result into errors. I used it in my compiler and it was cool. I had some functions which return `MonadError CodegenError a` and there were three different `MonadError CodegenError a` which I used (one of them is `Either` of course, also there were two my monads).

I think it would be good to use it here, for example: https://github.com/input-output-hk/pos-haskell-prototype/blob/master/src/Pos/FollowTheSatoshi.hs#L67

The problem is that there is no function `(MonadError e m, MonadError e' m') => (e -> e') -> m a -> m' a`, despite the fact that there is `withExceptT` and `mapLeft`.

Another problem is that almost all our pure code ends in `acid-state` `Update` which doesn't support anything to report errors, so we have to use `throw :: Exception e => e -> a`, that's why `MonadThrow` is better suited there.

Anyway, I see that my arguments are not convincing enough, but I have a feeling that `MonadError` is cool and should be used in pure code which can fail :)

> get rid of `catch` and whatsoever

What's a problem with `catch`? It contradicts with this statement:

> so at least these classes and their members should be imported

As I said in the first part, we need `catch :: (MonadCatch m, Exception e) => m a -> (e -> m a) -> m a`. It's a nice generalization of `Control.Exception.catch`.

> Problem was in `catch`, imported from some standard packages, not from `Monad.Catch`. And it was not obvious at all

This standard package is `base`. I don't see anything surprising in the fact that function from `base` is in `Universum`. I think it's what should be expected by default. Probably it would be better if `catch` from `exceptions` package was called `catchM` or something (like `throwM`), but that should be addressed to `exceptions` author, not to us.

**Comment by georgeee** [comment]
@gromakovsky I've talked about this one:
`Control.Exception.catch`. Presence of it in code, that uses generalized `throwM` is really confusing.

Also, Ok, `MonadError` might be a good thing. But I don't find it a good idea to include it into `Universum` when we already have `MonadCatch` stack.

**Comment by gromakovsky** [comment]
@neongreen and @ChShersh I think we have come to agreement about some points discussed here. For example, that some functions (e. g. `catch`) should be replaced with versions which use `MonadCatch`. Please do it unless if you have something to say.

**Comment by gromakovsky** [comment]
Regarding `MonadError` stuff. I think it's fine to remove it from `Universum`. Not because it conflicts with `Control.Monad.Catch` stuff (it doesn't and I see nothing bad in using both, they are for slightly different situations, imo), but because it's not popular (and probably won't become popular) to be in `Universum`. If we start using it actively at some point, we can include it, just like we include the most popular `mtl` monads, i. e. `MonadState` and `MonadReader`.

**Comment by ChShersh** [comment]
@gromakovsky @georgeee Ok, so my decision is to replace old version of `catch` with more general (would it be a good idea to call it `catchM`? I don't mind). Also I will export `MonadThrow`, `MonadCatch` and `MonadMask` type classes, hiding `MonadError`. I will also remove `throwIO` & `ioError` functions. Also I will remove `Control.Monad.Except` module if no one objects. Seems like nobody uses `ExceptT`, `runExceptT` and other stuff.

Moreover, I want to here from @gromakovsky what exact functions from `Control.Exception` do you need? I don't like idea of exporting everything from it because this module has functions like `asyncExceptionToException`. They are very specific. And this module also has a lot of other shit which is not supposed to be imported automatically. I'm for leaving only:

* `Exception`
* `SomeException`
* maybe `assert` if Ivan wants it.

Also `bracket` function should be lifted to `MonadIO`.

**Comment by gromakovsky** [comment]
> Also `bracket` function should be lifted to `MonadIO`.

Why not use `Control.Monad.Catch.bracket`?

> Moreover, I want to here from @gromakovsky what exact functions from Control.Exception do you need?

First of all I want to clarify that (as I already said) I want versions from `Control.Monad.Catch` (e. g. `bracket` from there), not from `Control.Exception`.

What I want to add to your list:
• `bracket_`
• `finally`
• `catchAll` maybe (from `Control.Monad.Catch`)? We often have long-running workers which really want to catch everything.

I think that should be enough for now.

**Comment by ChShersh** [comment]
Now `Universum` conflicts a lot with `Mockable` instances from `time-warp-nt`.

**Comment by gromakovsky** [comment]
AFAIK, exceptions-related `Mockable` will be removed from `node-sketch`.

**Comment by ChShersh** [comment]
I think this issue can be closed because now we use `Control.Exception.Safe`. If some conflicts happen in future new issue can be open.
