### ISSUE TITLE
Consider replacing text-format dependency

### ISSUE THREAD

**Issue by brandonhamilton** [serokell/universum#157]
`text-format` does [not currently compile with ghc-8.4](https://github.com/bos/text-format/issues/22) and appears to be unmaintained. Due to this it is no longer included in the latest stackage-nightly.

It seems that [dhall has taken the route](https://github.com/dhall-lang/dhall-haskell/pull/330) of replacing this dependency with the [formatting](https://hackage.haskell.org/package/formatting) library, which appears to offer a drop-in replacement for  `Data.Text.Buildable`.

**Comment by ChShersh** [comment]
Hi, @brandonhamilton! Unfortunately, migration to `formatting` is not possible at this moment.

`formatting` package has more dependencies than `text-format` which is kinda sad for custom prelude.

But most importantly: `universum` is used in one of the biggest projects — [`cardano-sl`](https://github.com/input-output-hk/cardano-sl). And moving this project from `text-format` to `formatting` is a huge work. Especially when migration to `GHC-8.4.1` won't happen for a long time.

Also, I don't want to use `formatting` library for formatting. We have `text-format` in dependencies for `universum` only because we need `Buildable` instances for some formatting library. But it's suggested to use [`fmt`](https://github.com/aelve/fmt) package for formatting because it's better. Maybe one day we will replace `text-format` with `fmt` in `universum`. Ping @neongreen for details.

I would like to have `Buidable` type class bundled with `text` package. I even opened an issue for this:

* https://github.com/haskell/text/issues/214

But looks like this won't happen soon as well.

Another possibilty: migrate to `display` package, which contains only `Buildable` type class and nothing redundant.

* http://hackage.haskell.org/package/display

But this involves migration of `fmt` to `Display` type class as well which is not possible because there's no `IsString` instance for `ByteString` `Builder` at the moment:

* https://github.com/aelve/fmt/issues/13

I opened issue for this as well:

* https://github.com/haskell/bytestring/issues/149

**Comment by brandonhamilton** [comment]
Great, thanks for this!

I am using `universum` in most of my projects, and `text-format` seems to be the blocker for migrating to ghc 8.4 :(

**Comment by ChShersh** [comment]
> I am using universum in most of my projects

Wow, that's nice to hear! I didn't imagine that people outside @Serokell use `universum` as a custom prelude. That's really motivating to continue doing this project better :muscle: If you use `stack` build and don't publish your packages to Hackage, you can use github dependency from your fork.

I would like @neongreen to join this conversation. I've created issue for this:

* https://github.com/aelve/fmt/issues/17

I will leave your PR open in case this problem can be solved somehow in nearest future.

**Comment by neongreen** [comment]
@brandonhamilton if you can make a PR to address https://github.com/aelve/fmt/issues/17 (nothing complicated), we can probably be done with that in no time.

**Comment by neongreen** [comment]
https://hackage.haskell.org/package/fmt-0.6
