### ISSUE TITLE
Think about 'microlens-*' deps

### ISSUE THREAD

**Issue by chshersh** [serokell/universum#182]
This is an extra dependency if you don't use lenses. This is also an extra dependency if you use `lens` library instead. But if your application has a lot of dependencies, you probably has `microlens` in dependencies anyway.

One possible solution is to add two extra compile-time flags:

* `lens`
* `microlens`

And reexport things depending on which flag is enabled. But probably you can't have `universum` in dependencies there one library uses it with one flag and other library –– with second flag.

**Comment by dcastro** [comment]
I, too, agree that `universum` should not re-export `microlens`.

Once you outgrow `microlens` and start needing `lens` (because, e.g., you need prisms), then using `Universum` stars becoming cumbersome.

`microlens`'s operators and function names clash with `lens`'s, which means you have to manually hide all the `microlens` operators/functions, one by one.

```hs
import Universum hiding ((^.), (^..), (^?), etc, ...)
import Control.Lens
```

@gromakovsky , what do you think? Should we remove the re-export?

**Comment by gromakovsky** [comment]
So there are actually 2 problems when you use `lens` and `universum`:
1. You transitively depend on both `lens` and `microlens`.
2. There are name clashes.

The former seems minor because:
> But if your application has a lot of dependencies, you probably has `microlens` in dependencies anyway.

The latter actually seems sad. I think these 2 reasons combined are enough to remove `microlens` or at least conflicting items. It's good that we already have a PR with this change: https://github.com/serokell/universum/pull/183/files, so we can see the impact.

I would keep `(&), (<&>)` because they are sometimes useful when you don't use lenses.
We can also keep `Lens, Lens', Traversal, Traversal'` because they are mere type synonyms which require nothing but `Functor`/`Applicative` and shouldn't conflict with anything. We don't really need to depend on `microlens`, we can define them directly in Universum. Maybe there are other things we can keep without conflicting with `lens`/`microlens` and not depending on `microlens`. At least one good reason to keep them is to minimize the number of breaking changes.

**Comment by dcastro** [comment]
> I think these 2 reasons combined are enough to remove microlens or at least conflicting items. It's good that we already have a PR with this change: https://github.com/serokell/universum/pull/183/files, so we can see the impact.

Awesome! @vrom911 fo you mind if we restore your branch and make the necessary changes to it?

> I would keep (&), (<&>) because they are sometimes useful when you don't use lenses.

Agreed, we can just re-export them from `base`.

> We can also keep Lens, Lens', Traversal, Traversal' because they are mere type synonyms which require nothing but Functor/Applicative and shouldn't conflict with anything. 

This should be ok if we're using combinators from lens.

But if we were defining our own combinators (e.g. `myCombinator :: Lens' s a -> Lens' a b -> Lens' s b `), then we'd have a clash between `Control.Lens.Lens'` and `Universum.Lens'`, right?

**Comment by gromakovsky** [comment]
> But if we were defining our own combinators (e.g. `myCombinator :: Lens' s a -> Lens' a b -> Lens' s b` ), then we'd have a clash between `Control.Lens.Lens'` and `Universum.Lens'`, right?

I think there shouldn't be any clash because `type Lens s t a b = forall f. Functor f => (a -> f b) -> s -> f t ` in all libraries and `Functor` comes from `base` anyway, so the type is `myCombinator :: (forall f. Functor f => (a -> f a) -> s -> f s) -> …` in both cases. If `Lens` was a newtype, it would be a problem, but it's not.

**Comment by dcastro** [comment]
Hm I just gave this a try, and it seems that in the presence of two type synonyms with the same name and the same rhs, references can still be ambiguous:


```hs
module A where
type T = Int
```

```hs
module B where
type T = Int
```

```hs
module C where

import A
import B

x :: T
x = 0
```

```
Ambiguous occurrence ‘T’
It could refer to
   either ‘A.T’,
          imported from ‘A’ at /home/dc/dev/serokell/o-clock/src/C.hs:3:1-8
          (and originally defined
             at /home/dc/dev/serokell/o-clock/src/A.hs:3:1-12)
       or ‘B.T’,
          imported from ‘B’ at /home/dc/dev/serokell/o-clock/src/C.hs:4:1-8
          (and originally defined
             at /home/dc/dev/serokell/o-clock/src/B.hs:3:1-12)
```

**Comment by vrom911** [comment]
@dcastro sure, go for it 👍🏼 
Thanks for reaching out, btw :)

**Comment by gromakovsky** [comment]
> Hm I just gave this a try, and it seems that in the presence of two type synonyms with the same name and the same rhs, references can still be ambiguous:

Oh, I didn't know that, okay then. So previously I was totally for exporting these type synonyms, now I am not sure (not for it, but also not against it). It doesn't sound like a big problem because if `Lens` is implicitly imported from `Universum` you simply won't import it from `Control.Lens` (or `microlens` equivalent). And if you have `a :: Universum.Lens s t a b` you can pass it to `f :: Control.Lens.Lens s t a b -> foo` defined somewhere else.

I mean, even if you copy-pasted code with `import Control.Lens (Lens)` into a place where `Universum` is implicitly imported, it would't be a bad idea to remove this import even if it didn't conflict with `Universum.Lens` (i. e. we typically try to minimize the number of imports and remove identical imports coming from multiple places).

**Comment by dcastro** [comment]
I see what you mean. Even if you have similar type synonyms defined in both libraries, you could still define values using one library's type syns and be able to pass it to the other library's functions.

However, I don't see what the benefit of exporting _just_ the type syns from universum is...
I only see disadvantages: as you pointed out, the user would sometimes have to hide the type synonyms from either `lens` or `universum`.

I think most `lens` users just import the entire `Control.Lens` module, without an explicit import list, especially when making heavy use of the library. But with this change, they'd have to do something like `Control.Lens hiding (Lens, Lens', etc)`.

**Comment by gromakovsky** [comment]
The main advantage is to minimize the number of breaking changes, so that code where `Lens` is used without explicit import will still compile. As a middle ground, we can continue exporting these type synonyms and deprecate them for a while.
Oh well, strictly speaking, we should first make at least one release where we'll deprecate everything we want to delete and then delete it later in another release after enough time. Because every breaking change in prelude is very painful.

**Comment by dcastro** [comment]
Ah yes that's a very good point, let's just mark these as deprecated for now!

**Comment by dcastro** [comment]
> Oh well, strictly speaking, we should first make at least one release where we'll deprecate everything we want to delete and then delete it later in another release after enough time.

@gromakovsky thinking about this a bit more: can a re-export even be deprecated? :thinking: I don't think they can... we might have to just stop re-exporting these altogether.

**Comment by gromakovsky** [comment]
Oh, right, there is no way to deprecate re-exports 😞 A slightly hacky option is to replace re-exports with our own definition and deprecate them immediately. So for example we can define our own `type Lens s t a b = forall f. Functor f => (a -> f b) -> s -> f t ` and deprecate it saying that one should use `Lens` from the lens library of their choice (`lens` of `microlens`). It shouldn't affect `lens` users (because `Lens` will still be the same type and in some cases will conflict with `Control.Lens.Lens`), it may break something for `microlens` users, but removing `Lens` will break it too.

**Comment by dcastro** [comment]
This has been deprecated in #262, so I'm closing this issue.

I've created a follow-up issue https://github.com/serokell/universum/issues/268 to remove `microlens` completely in 1.9.0
