### ISSUE TITLE
Export more functions for Text

### ISSUE THREAD

**Issue by neongreen** [serokell/universum#2]
I'm thinking about `unwords`, `lines`, etc.

**Comment by ChShersh** [comment]
Agree. Those functions maybe useful. And because we remove some things from `Prelude` new user may expect difficulties when trying to apply good old and well-known functions. It should be possible to write something like `lines "Line 1\n Line2"` without extra effort. I'm looking forward to full list of such functions that we accidentally removed.

**Comment by ChShersh** [comment]
There are a lot of functions for `Text`. I'm voting for next functions: `lines` `unlines` `words` `unwords` `strip`. If nobody propose any new functions or disagree with me then I will add those and close issue.

**Comment by neongreen** [comment]
No objection from me.

**Comment by gromakovsky** [comment]
No obections.
