### ISSUE TITLE
Generalize andM and similar functions

### ISSUE THREAD

**Issue by gromakovsky** [serokell/universum#35]
Currently they only work on lists, but can be generalized I suppose.

**Comment by ChShersh** [comment]
Okay, seems like those functions indeed can be generalized. This seems to work:

```haskell
λ: let andM = foldr (\elem rest -> elem >>= \b -> if b then rest else pure False) (pure True) 
λ: :t andM
andM :: (Foldable t, Monad m) => t (m Bool) -> m Bool
λ: andM [Just True, Just False]
Just False
λ: andM [Just True, Just False, Nothing]
Just False
λ: andM [Just True, Nothing, Just False]
Nothing
λ: andM [putStrLn "1" >> pure True, putStrLn "2" >> pure False, putStrLn "3" >> undefined]
1
2
False
```

But don't know how it behaves with space leaks. Using `for` instead of `whenJust` introduces spaces leaks. That's why we have `whenJust` specialization. So I'm more cautious after that bug with such general definitions. @neongreen  Could you check this definition on space-leakiness?

**Comment by neongreen** [comment]
> I expect some bugs after converting [Maybe Bool] into Maybe [Bool]

This is not an issue if we use `NontrivialContainer` instead of `Foldable`.

> Using for instead of `whenJust` introduces spaces leaks.

Instead of your definition I would just use the original list definition together with `toList`, to be safe.

**Comment by gromakovsky** [comment]
The only drawback is that version with `toList` is probably less efficient in some cases.

**Comment by ChShersh** [comment]
We have https://github.com/serokell/universum/issues/21 for that ;)
But I don't expect noticeable performance degrade.
