### ISSUE TITLE
Use UTF-8 encoding when working with ByteString

### ISSUE THREAD

**Issue by neongreen** [serokell/universum#4]
Currently we use ASCII when converting `String` to `ByteString` (https://github.com/sdiehl/protolude/issues/21) and when printing a `ByteString`. I propose changing the first one to use `encodeUtf8` and adding a warning in the second case.

**Comment by gromakovsky** [comment]
Conversion between `String` and `Bytestring`: omg, it's very sad :(
Let's do something with it. Either add utf-8 encoding/decoding or even remove conversion between `String`/`Text` and `ByteString`, because semantics of these types is really different.
There is no unique way to convert `String` into `ByteString`, there are multiple ways to do it. And I think that in `universum` we should have only functions whose semantics is absolutely clear from type.
Printing `ByteString`: can you elaborate on it? Do you mean `Print` type class?

**Comment by neongreen** [comment]
> Do you mean Print type class?

Yep, in `Show.hs`.

**Comment by neongreen** [comment]
I think that converting between `Text` and `ByteString` is pretty unambiguous, people expect it to go through UTF-8. For `String` and `ByteString` it's harder.

Actually, frankly I don't like `toS` at all. It'd be nicer if there were:

```
encodeUtf8 :: (String | Text | LText) -> (ByteString | LByteString)
decodeUtf8 :: (ByteString | LByteString) -> (String | Text | LText)

toText :: (String | Text | LText) -> Text
toLText :: (String | Text | LText) -> LText
toString :: (String | Text | LText) -> String
```

**Comment by gromakovsky** [comment]
> I think that converting between Text and ByteString is pretty unambiguous, people expect it to go through UTF-8.

Yes, but once you are on Windows, this expectation may bite you :)
Remember that we are aiming to be crossplatform.

> Actually, frankly I don't like toS at all. It'd be nicer if there were:

Yes, I like it more. Semantics of conversion between ByteString and UnicodeString is different from semantics of conversion between two UnicodeStrings.
The second part is questionable, I am not sure if it's better to have three functions or one.

**Comment by neongreen** [comment]
> I am not sure if it's better to have three functions or one

It helps with mental type inference because now you know the output type just by looking at the function. I made the same choice in my [text-all](https://hackage.haskell.org/package/text-all) library.

Also, having one god-function `convert :: a -> b` usually leads to ambiguous types and you either have to add type annotations anyway, or use `asText` / `asString` / etc, a la classy-prelude.

**Comment by neongreen** [comment]
> Yes, but once you are on Windows, this expectation may bite you

Hm, I wasn't aware of this. In what circumstances might it bite me? (I know about almost-UTF-16 encoding for file names, but if you use a file path handling library, it's not an issue.)

**Comment by gromakovsky** [comment]
Yes, but at the same time if there is function which expects `String` and after some time it is rewritten and expects `Text`, we'll have to change all usages. With god-function it won't happen. That's the reason in favour of one function approach. Your reason is a good point in favour of three functions approach.

> Hm, I wasn't aware of this. In what circumstances might it bite me? (I know about almost-UTF-16 encoding for file names, but if you use a file path handling library, it's not an issue.)

AFAIK, on Windows files are usually not in utf-8 (at least it was earlier). If you read file as `ByteString`, do something with it and then somewhere else decode it assuming it is utf-8, you may have problems I guess.

**Comment by gromakovsky** [comment]
Let's do something with it until it's too late. This issue suggests making a breaking change and I don't want to make it after we write too much code which uses it.

My opinion:
1. Replace `toS` with 5 functions mentioned by @neongreen.
2. I don't care about presence of `ByteString` in `Print` class. I don't have any expectations when I print `ByteString` with non-ascii bytes to console anyway :)
I expect that it will some garbage.
Documentation of `BS.putStr` is `Write a ByteString to stdout`, so it is not really informative. But I don't care.

**Comment by rockbmb** [comment]
I think this is a good solution @neongreen @gromakovsky

**Comment by gromakovsky** [comment]
Everybody likes
```
encodeUtf8 :: (String | Text | LText) -> (ByteString | LByteString)
decodeUtf8 :: (ByteString | LByteString) -> (String | Text | LText)

toText   :: (String | Text | LText) -> Text
toLText  :: (String | Text | LText) -> LText
toString :: (String | Text | LText) -> String
```

Discussion is over. Please do it when you have time. And update `pos-prototype` accordingly.

**Comment by gromakovsky** [comment]
Guys, there is only one thing which I think is missing: where is a comment about leniency of `decodeUtf8`?
