### ISSUE TITLE
Add 'getState' and 'putState' because `identity .= blah` doesn't look good?

### ISSUE THREAD

**Issue by neongreen** [serokell/universum#47]

**Comment by int-index** [comment]
I like how `identity .= blah` looks.

**Comment by gromakovsky** [comment]
But `.=` is not exported too, so you can write `put blah` with the same number of explicit imports 🤷‍♂️

**Comment by ChShersh** [comment]
I like `putState` and `getState`. These names are more explicit. Also, it's not very clear how `identity .= blah` works. Especially when you're beginner. I don't like the fact that in order to use `State` you need to know lenses. As for me, lenses in `universum` should be pleasant addition but users of `universum` shouldn't be forced to use them.

**Comment by neongreen** [comment]
> so you can write put blah with the same number of explicit imports

But I don't want to use `put` because it's also used in binary code. I dunno. Maybe we don't actually have code that uses both binary and state, and then it's alright.

**Comment by ChShersh** [comment]
@neongreen I think @gromakovsky wanted to say that it doesn't make sense to compare w/ `identity .= blah` because `universum` doesn't export `.=` so in terms of resulting number of imports these approaches are equivalent. We either export `(.=)` operator (which I don't like) or add `putState` and `getState` (which I like). We don't have `put` and `get` currently exported which I also like.

**Comment by neongreen** [comment]
@ChShersh maybe we can export `put` and `get` since we don't use `binary` anymore and thus they don't conflict with our code?

**Comment by ChShersh** [comment]
@neongreen Yes, I think we can do it. I skimmed through _Stackage_. `put` and `get` are used mainly from `transformers` and `mtl`. It's really rare that people we have different `put` and `get`. And `binary` probably shouldn't be used. Or always can be used qualified. But I think that for almost every Haskell programmer `put` and `get` have `State`ish meaning.
