### ISSUE TITLE
Figure out what to do with unsafe `head` and friends

### ISSUE THREAD

**Issue by neongreen** [serokell/universum#5]
Currently:
- `Unsafe` exports `unsafe(Head|Tail|Init|Last|At)`
- `head` returns `Maybe`
- `tail`, `init`, `last`, `(!!)` aren't exported at all
- functions from safe (e.g. `atMay`, `atDef`, `headMay`, `headDef`) are exported by default

I don't have a strong preference here – the only thing I kinda want to do is to remove `head`. Otherwise I'm slightly in favor of removing `unsafe*` variants and adding unsafe `head`, etc. back while retaining safe variants, but I'm okay with not doing it. What do others think?

**Comment by ChShersh** [comment]
Why do you want to remove `head`? This function is well-known and very useful. And I can tell about one important use case: pattern matching on `Text` types with `ViewPatterns`. Because `Text` is completely different type than `String` we cant write:

```haskell
caseMode :: Text -> Mode
caseMode ('R':_) = ReadMode
caseMode ('W':_) = WriteMode
```
But this can be very useful. Having safe `head` function we can write almost the same but in more verbose way:
```haskell
caseMode :: Text -> Mode
caseMode (head -> Just 'R') = ReadMode
caseMode (head -> Just 'W') = WriteMode
```

So I claim this function (and family) is actually useful. I want to leave safe version of of `head`, I want to add safe versions of `tail`, `init`, `last`, `!!` and export them. And I want to leave  `unsafe(Head|Tail|Init|Last|At)`. Also I want to add warnings on all unsafe functions.

**Comment by neongreen** [comment]
I want to remove `head` because it's different from what literally every Haskeller is already used to. I'd rather use `headMay` explicitly when I want `head` that returns `Maybe`. (Safe versions of `tail` etc. are also already available as `tailMay` and so on.)

By the way, your proposed example with `Text` won't work anyway because `Text` isn't `Foldable`:

```haskell
head :: Foldable f => f a -> Maybe a
```

**Comment by ChShersh** [comment]
Ah, okay, I got your idea. So we can export `safe(Head|Tail|Init|At)`. We can leave `head` and company. And just put warnings on unsafe versions. But regarding removing `head`... I expect this will hurt a lot. But this function is bad so I'm okay with it :)

Sure, you're right. I was thinking about `head` function from `text` package. We can make something cool with those functions.

**Comment by neongreen** [comment]
I like the idea of using pattern synonyms for such things:

``` haskell
> import Control.Lens
> import Data.Text (Text)
> :set -XOverloadedStrings

> let (x:<_) = "abc" :: Text in x
'a'

> let (x:<_) = "" :: Text in x
*** Exception: <interactive>:10:5-23: 
    Irrefutable pattern failed for pattern (x :< _)
```

**Comment by neongreen** [comment]
They can be used both for consing and unconsing, too:

```
> 'a' :< ("bc" :: Text)
"abc"
```

**Comment by neongreen** [comment]
And, of course, they're actual patterns so you can match on them:

```haskell
caseMode ('R':<_) = ReadMode
caseMode ('W':<_) = WriteMode
```

**Comment by ChShersh** [comment]
@neongreen Now, because you introduces `NonTrivialContainer` analogue to `Foldable` for `Text`:
https://github.com/serokell/universum/blob/master/src/Containers.hs#L115

We can finally create such pattern for `Data.Text` and probably every `NonTrivialContainer`. Is it possible to create `PatternSynonym` for every instance of type class at once?
Also, it's better to name it `:?` (as it seems to me).

**Comment by ChShersh** [comment]
I think we should add `tail`, `init`, `last` and `!!` safe versions without exporting `atMay, tailMay`, etc.
We can keep `tailDef` and company, those functions maybe useful.
Also, do we want go crazy and use _type family_ tricks to allow `head` and company return `a` instead of `Maybe a` for `NonEmpty`?

**Comment by ChShersh** [comment]
I propose to resolve this issue for now in the next way:

1. `head :: [a] -> Maybe a`
2. `tail :: [a] -> [a]; tail = drop 1` (doesn't throw exception on empty list)
3. `init :: [a] -> [a]` (also doesn't throw exception on empty list)
4. `last :: [a] -> Maybe a` (safe version)

This allows to have these four functions but in safer variant.

**Comment by int-index** [comment]
I'd rather have

1. `head :: NonEmpty a -> a`
2. `tail :: NonEmpty a -> [a]`
3. `init :: NonEmpty a -> [a]`
4. `last :: NonEmpty a -> a`

One could easily get back the `Maybe`-based safe versions by using `nonEmpty`.

**Comment by int-index** [comment]
I'm against `tail = drop 1` because this will lead to unexpected behavior and silent failures.

**Comment by ChShersh** [comment]
@int-index Well, in that case, why not have both? Which is what was my previous proposal:

```haskell
class HasHead f where
    type Head f
    head :: f -> Head f

instance HasHead [a] where
    type Head [a] = Maybe a
    head = ...

instance HasHead (NonEmpty a) where
    type Head (NonEmpty a) = a
    head = ...
```

In that case we can even have polymorphic `head` which works for `Text` and `ByteString` as well.

I'm not a big fan of such approach, because the idea of `universum` was to stick to some reasonable defaults. But having both `head :: [a] -> Maybe a` and `head :: NonEmpty a -> a` is better than only one of such functions.

**Comment by int-index** [comment]
I would rather have separate functions for getting the head of non-empty collections and converting possibly-empty collections to non-empty ones.

That is, I think `head` of a `NonEmpty` list and `head` of a regular `[]` are fundamentally different operations. There are other axes along which you could add polymorphism, for example, you could have `head :: Alternative f => [a] -> f a` (where `f = Maybe` is one possible choice).

I don't like using classes solely for name overloading because it only complicates type errors. Writing `fmap head . nonEmpty` is really not that difficult.

**Comment by int-index** [comment]
One could even write `head <<$>> nonEmpty`, I believe.

**Comment by ChShersh** [comment]
@int-index Your arguments are very convincing. It's now more clear what to do with such functions. Thanks for your discussions! Only several leftovers:

1. I think `fmap head . nonEmpty` or `head <<$>> nonEmpty` will occur rather often it's better to create helper function for this. Moreover, [such function already exist](http://hackage.haskell.org/package/base-4.10.0.0/docs/Data-Maybe.html#v:listToMaybe) and I think we should reexport it.
2. What do you think about exporting `(head|tail|last|init|at)(Def|May)` from `safe` package? Do we still need such reexport, is it really that useful to have such functions always in scope?

**Comment by int-index** [comment]
Having `listToMaybe` and `maybeToList` in scope sounds good.

I'm not sure about `Def` and `May` varieties of functions, because, once again, I think getting the `May` variety from `NonEmpty` is trivial with `nonEmpty` and getting the `Def` variety is trivial with `fromMaybe`.

So I would write `headDef d` as `maybe d head . nonEmpty`.

**Comment by kirelagin** [comment]
I kinda feel @neongreen’s concerns that having `head` with a different signautre is going to be confusing, if `universum` is potentially aimed not only at the professionals, who know exactly what they are doing, but to beginners that are not 100% sure, because seing that a function does not exist at all is a storonger and much more clear signal than getting a type checking error.

Furthermore, to be honest, I don’t see any value at all in keeping the names of these functions, writing `headMay` or whatever is not that much more difficult than `head`. So, I’d say, make them all return `Maybe` and add the `May` (or whatever) suffix. Remove the versions that are unsafe or that behave completely differently (e.g. do not throw exceptions on empty lists, where the standard ones do).

**Comment by kirelagin** [comment]
This is all assuming that we are exporting them at all. Honestly, though, I’m not really sure why export them at all. In real world applications lists are used not that often, and I can’t see why I need to export `Map` functions explicitly, while I get (a random subset of) list functions for free.

**Comment by ChShersh** [comment]
@kirelagin This issue is mostly opinionated. I don't think there might be some general solution that can satisfy everyone.

> if universum is potentially aimed not only at the professionals, who know exactly what they are doing, but to beginners that are not 100% sure

Who do you call _beginner_? `universum` is aimed at people who will read `universum` tutorial first before starting using this library. And README describes (and will describe even better) all things _beginners_ need to know. `universum` is not aimed at people who will just randomly replace default prelude with `universum` and will start coding. If _beginner_ is someone new in our company, he can always ask questions in our #universum slack channel :) After reading tutorial, of course. And if he reads he won't be surprised by such type signature.

> because seing that a function does not exist at all is a storonger and much more clear signal than getting a type checking error.

Clear signal for what? I don't think that error message in form of _you don't have such function_ is much better than type error. In both cases person doesn't know what to do. In first case he will be motivated to learn about `NonEmpty`. In second he will just use ugly pattern matching and he will hate `universum` for not providing convenient utilities :) Also true beginner is most likely not aware of `safe` package to come up with functions by his own. Because of that it's not obvious to come up with `head(May|Def)` name.

> writing headMay or whatever is not that much more difficult than head

It's more difficult if you use `NonEmpty` a lot because `headMay` doesn't work with `NonEmpty`.

> So, I’d say, make them all return Maybe and add the May

I was convinced by @int-index that having functions to work with `NonEmpty` is better rather than having them return `Maybe`.

> Remove the versions that are unsafe or that behave completely differently

Such versions will be removed.

>  In real world applications lists are used not that often

You underestimate number of list usages. Lists are used quite often. Maybe they don't have size like `10^6` but this is rather common data structure. For me it's more weird to not provide convenient functions to work with lists. And `NonEmpty` is also used more often that you think :smirk: Or at least should be used more often.

> I can’t see why I need to export Map functions explicitly, while I get (a random subset of) list functions for free.

I don't like exporting functions from `Map`-like module implicitly. If I see `lookup` in code I'm not sure which one it is: `HashMap.lookup` or `Map.lookup` or `NonEmpty.lookup` or `IntMap.lookup` or `Vector.lookup` or something else? While we don't have polymorphic interfaces for `Map`-like data structures qualified imports for such cases are better to me.
